# Generated by Django 3.2.4 on 2021-06-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table=None,
        ),
    ]
